@call ..\export.cmd %1 %2 "Coremoran - Unit - Assertions"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - All (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Any (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Average (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Count (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - FirstOrDefault (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - GroupBy (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - GroupJoin (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Join (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - LastOrDefault (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Max (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Min (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - OrderBy (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Page (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Reverse (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Select (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - SelectMany (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - SelectMany2 (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - SingleOrDefault (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Skip (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - SkipWhile (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Sum (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Take (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - TakeWhile (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ - Where (Tests)"
@call ..\export.cmd %1 %2 "Coremoran - Dynamic LINQ (Testsuite)"